# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lightdrop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  # Pods for Lightdrop

  target 'Lightdrop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-config', :path => '../node_modules/react-native-config'

  end

  target 'LightdropTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Lightdrop-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

end
